### ISSUE TITLE
ERROR TypeError: elem_1 is undefined

### ISSUE THREAD

**Issue by ritunjaykumar** [sascha10000/ngx-qr-with-image#5]
```
<qr-img   content="content_shown_by_qr_code" img="assets/imgs/logo.png" size="200" img-width="30" img-height="30"
    (change)="someFunction($event)">
  </qr-img>
```

How can i resolve this issue.

**Comment by sascha10000** [comment]
Please tell me more about the error. There is no elem_1 in the code as far as i know. Maybe remove some of the non-mandatory attributes.

**Comment by ritunjaykumar** [comment]
I was getting only that much error only

**Comment by sascha10000** [comment]
Is it still relevant? If yes reference the part of your code or elaborate at least what you did with the code snippet and that sparsely info I can barely help you. Because the example is working and there is no variable elem_1. It would be possible that it is some angular internals.
