### ISSUE TITLE
Unable to specify height for the QR Code

### ISSUE THREAD

**Issue by Psyora-appsy01** [sascha10000/ngx-qr-with-image#6]
In the Source Code, the height property is set to iWidth.

![image](https://user-images.githubusercontent.com/48180347/159106500-33c1131e-5580-46b8-892f-1041eded1162.png)

Also, there is an error in the spelling of imgHeight

![image](https://user-images.githubusercontent.com/48180347/159106490-c03704c8-8b6b-4623-8fb7-c1bbfa4d5fab.png)

**Comment by sascha10000** [comment]
Thanks for your feedback. I will fix those issues. I didn't see , until a friend told me today, that this repo is actually used.

**Comment by sascha10000** [comment]
Thanks for this detailed error description
